### ISSUE TITLE
Cannot create new corgi when using "yarn start"

### ISSUE THREAD

**Issue by mikedotexe** [nearprotocol/corgis#4]
There is a Timeout (which could be any error, unfortunately) that occurs on `master` that does not occur when creating a new corgi on:
https://corgis.near.org/

Users cannot create a new corgi after following the instructions to the README, even after they figure out that they need an additional step of `near deploy`

<img width="878" alt="Screenshot 2020-05-12 10 57 04" src="https://user-images.githubusercontent.com/1042667/81728999-2521a080-9440-11ea-9aa3-2eeea015c77a.png">

**Comment by icerove** [comment]
I change some script in package.json. The first time deploy is a little different since I do not want to dev-deploy every time. Add `--init` after script `near dev-deploy` first time. Every other time not needed

**Comment by icerove** [comment]
use `yarn dev` instead of `yarn start` is better.

**Comment by icerove** [comment]
can you try again, I think it works now following the the readme instruction.
@mikedotexe

**Comment by mikedotexe** [comment]
Great, thank you
